apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv-extensions
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: sonarqube-pvc-extensions
    namespace: tools-app
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/smart-recrut/config/tools-app/sonarQube-pv/sonarQube-pv-extensions
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
