apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: jenkins-pvc-data
    namespace: tools-app
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/smart-recrut/config/tools-app/jenkins-pv/jenkins-pv-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
