apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-postgres-config-map
  namespace: tools-db
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "tools-app"
data:
  sonarqube-postgres-db-db: sonarqube
  sonarqube-postgres-db-url: jdbc:postgresql://sonarqube-postgres-service.tools-db.svc:5432/sonarqube
