apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-postgres-pv-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: sonarqube-postgres-pvc-data
    namespace: tools-db
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/smart-recrut/config/tools-db/sonarQube-postgres-pv/sonarQube-postgres-pv-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
