apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgres-service
  namespace: tools-db
  labels:
    name: sonarqueb-postgres-server
spec:
  selector:
    app: sonarqube-postgres-server
  ports:
    - port: 5432
      targetPort: 5432
