apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secrets
  namespace: tools-db
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tools-app"
type: Opaque
data:
  keycloak-postgres-db-user: YWRtaW4=
  keycloak-postgres-db-password: YWRtaW4=
