apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
  namespace: tools-db
  labels:
    name: sonarqueb-postgres-server
spec:
  selector:
    app: keycloak-postgres-server
  ports:
    - port: 5432
      targetPort: 5432
